import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '@/components/Header';
import Providers from '@/components/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${inter.className} bg-slate-50`}>
                <Providers isDev={process.env.NODE_ENV !== 'production'}>
                    <Header />
                    <main className='container mx-auto'> {children}</main>
                </Providers>
            </body>
        </html>
    );
}
